import json
import httpx
from typing import Dict, Any, List
from openai import OpenAI
from app.core.config import settings


class LLMService:
    """
    Multi-Provider LLM Service.
    Seamlessly routes requests to Google Gemini, OpenAI, or Offline Fallback.
    """
    def __init__(self):
        self._openai_client = None

    @property
    def openai_client(self) -> OpenAI:
        if self._openai_client is None and settings.is_openai_configured:
            self._openai_client = OpenAI(api_key=settings.OPENAI_API_KEY)
        return self._openai_client

    def test_completion(self, prompt: str) -> Dict[str, Any]:
        """Tests connectivity with the active provider (Gemini, OpenAI, or Fallback)."""
        provider = settings.active_provider

        # 1. Google Gemini via Fast REST API
        if provider == "gemini" and settings.is_gemini_configured:
            try:
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{settings.GEMINI_MODEL}:generateContent?key={settings.GEMINI_API_KEY}"
                payload = {
                    "contents": [{"parts": [{"text": prompt}]}]
                }
                with httpx.Client(timeout=15.0) as client:
                    r = client.post(url, json=payload)
                    if r.status_code == 200:
                        text_resp = r.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
                        return {
                            "prompt": prompt,
                            "response": text_resp,
                            "model": f"Google Gemini ({settings.GEMINI_MODEL})",
                            "provider": "gemini",
                            "is_mock": False
                        }
                    else:
                        return {
                            "prompt": prompt,
                            "response": f"Gemini API Error (HTTP {r.status_code}): {r.text}",
                            "model": settings.GEMINI_MODEL,
                            "provider": "gemini",
                            "is_mock": True
                        }
            except Exception as e:
                return {
                    "prompt": prompt,
                    "response": f"Gemini API Error: {str(e)}",
                    "model": settings.GEMINI_MODEL,
                    "provider": "gemini",
                    "is_mock": True
                }

        # 2. OpenAI
        if provider == "openai" and settings.is_openai_configured:
            try:
                completion = self.openai_client.chat.completions.create(
                    model=settings.OPENAI_CHAT_MODEL,
                    messages=[
                        {"role": "system", "content": "You are an expert Social Value advisor for public tenders."},
                        {"role": "user", "content": prompt}
                    ],
                    max_tokens=250,
                    temperature=0.2
                )
                return {
                    "prompt": prompt,
                    "response": completion.choices[0].message.content.strip(),
                    "model": f"OpenAI ({settings.OPENAI_CHAT_MODEL})",
                    "provider": "openai",
                    "is_mock": False
                }
            except Exception as e:
                return {
                    "prompt": prompt,
                    "response": f"OpenAI API Error: {str(e)}",
                    "model": settings.OPENAI_CHAT_MODEL,
                    "provider": "openai",
                    "is_mock": True
                }

        # 3. Offline Mode
        return {
            "prompt": prompt,
            "response": (
                "[OFFLINE DEMO MODE] Social Value represents the wider positive social, "
                "economic, and environmental benefits generated by public procurement and corporate activities."
            ),
            "model": "offline-fallback-mode",
            "provider": "offline",
            "is_mock": True
        }

    def generate_recommendation_from_llm(
        self,
        context_text: str,
        opportunity: Dict[str, Any],
        toms_catalog: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Sends retrieved knowledge + RFP requirements to the active LLM (Gemini or OpenAI)
        and parses structured JSON recommendation.
        """
        system_prompt = (
            "You are the Infosys Social Value RFP Response Architect.\n"
            "Your job is to produce a structured tender recommendation tailored to the client's requirements.\n\n"
            "CRITICAL RULES - DO NOT HALLUCINATE:\n"
            "1. Ground initiatives in the provided RETRIEVED EVIDENCE whenever possible.\n"
            "2. Distinguish between:\n"
            "   - Information grounded in source documents (is_from_knowledge_base = true)\n"
            "   - Model-generated proposals based on best practice (is_from_knowledge_base = false)\n"
            "   - Explicit assumptions\n"
            "   - Items requiring validation (validation_required)\n"
            "3. If the knowledge base does not provide a specific partner, cost, or local entity, DO NOT INVENT ONE. "
            "Instead, set partner to null and add a note to 'validation_required'.\n"
            "4. Map each initiative to an appropriate National TOMs metric code from the PROVIDED TOMs CATALOG (e.g., NT1, NT3, NT8, NT10, NT14, NT20).\n"
            "5. Do NOT perform arithmetic or final financial calculations; simply estimate realistic annual_volume for each initiative.\n"
            "6. You must return ONLY a valid JSON object matching the exact JSON schema requested."
        )

        user_content = f"""
OPPORTUNITY DETAILS:
- Client: {opportunity.get('client')}
- Location: {opportunity.get('location')}
- Contract Duration: {opportunity.get('contract_duration_years')} years
- Contract Value: £{opportunity.get('contract_value_gbp'):,}
- Social Value Target Weighting: {opportunity.get('social_value_weighting_percent')}%
- Client Priorities: {', '.join(opportunity.get('priorities', []))}

AVAILABLE TOMs METRIC PROXY CATALOG:
{json.dumps(toms_catalog, indent=2)}

RETRIEVED KNOWLEDGE BASE EVIDENCE:
{context_text if context_text.strip() else "No direct historical documents found. Please recommend standard best-practice initiatives and flag validation required."}

Produce a JSON response with this exact structure:
{{
  "core_package": {{
    "rationale": "High confidence, baseline package addressing core contractual compliance",
    "initiatives": [
      {{
        "name": "Initiative Title",
        "theme": "Theme matching priority",
        "location": "{opportunity.get('location')}",
        "description": "Clear delivery scope",
        "delivery_mechanism": "e.g. 4 workshops per year",
        "target_beneficiaries": "Beneficiary group",
        "annual_volume": 4.0,
        "toms_metric_code": "NT8",
        "partner": "Partner name if found in evidence, else null",
        "evidence_source": "Source document title or 'Recommended best practice'",
        "is_from_knowledge_base": true
      }}
    ],
    "expected_impact": ["Impact bullet 1"],
    "dependencies": ["Key dependency 1"]
  }},
  "enhanced_package": {{
    "rationale": "Expanded high-value package to win competitive bids",
    "initiatives": [...],
    "expected_impact": [...],
    "dependencies": [...]
  }},
  "localised_package": {{
    "rationale": "Hyper-localised package customized specifically for {opportunity.get('location')}",
    "initiatives": [...],
    "expected_impact": [...],
    "dependencies": [...]
  }},
  "assumptions": [
    "Assumption regarding delivery, resources, or timeline"
  ],
  "validation_required": [
    "Commercial, partner availability, or local council alignment points needing bid team confirmation"
  ]
}}
"""

        provider = settings.active_provider

        # 1. Google Gemini Provider via Fast REST API
        if provider == "gemini" and settings.is_gemini_configured:
            try:
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{settings.GEMINI_MODEL}:generateContent?key={settings.GEMINI_API_KEY}"
                payload = {
                    "contents": [{"parts": [{"text": f"{system_prompt}\n\n{user_content}"}]}],
                    "generationConfig": {"responseMimeType": "application/json"}
                }
                with httpx.Client(timeout=30.0) as client:
                    r = client.post(url, json=payload)
                    if r.status_code == 200:
                        raw_json = r.json()["candidates"][0]["content"]["parts"][0]["text"]
                        return json.loads(raw_json)
                    else:
                        print(f"[LLMService] Gemini HTTP {r.status_code}: {r.text[:200]}")
            except Exception as e:
                print(f"[LLMService] Gemini error: {e}. Falling back to grounded structure.")
                fallback = self._generate_offline_fallback(opportunity, context_text)
                fallback["validation_required"].append(f"Gemini API warning: {str(e)}")
                return fallback

        # 2. OpenAI Provider
        if provider == "openai" and settings.is_openai_configured:
            try:
                response = self.openai_client.chat.completions.create(
                    model=settings.OPENAI_CHAT_MODEL,
                    response_format={"type": "json_object"},
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_content}
                    ],
                    temperature=0.2
                )
                return json.loads(response.choices[0].message.content)
            except Exception as e:
                print(f"[LLMService] OpenAI error: {e}. Falling back to grounded structure.")
                fallback = self._generate_offline_fallback(opportunity, context_text)
                fallback["validation_required"].append(f"OpenAI API warning: {str(e)}")
                return fallback

        # 3. Offline Mode
        return self._generate_offline_fallback(opportunity, context_text)

    def _generate_offline_fallback(self, opportunity: Dict[str, Any], context_text: str) -> Dict[str, Any]:
        """Provides a grounded deterministic response when running without live external credentials."""
        loc = opportunity.get("location", "Birmingham")
        has_context = bool(context_text and "Birmingham" in context_text)

        return {
            "core_package": {
                "rationale": f"Baseline Social Value package tailored to {loc} contract priorities.",
                "initiatives": [
                    {
                        "name": f"{loc} Digital Skills & Inclusion Clinics",
                        "theme": "Digital Inclusion",
                        "location": loc,
                        "description": "Quarterly community digital inclusion workshops focusing on digital literacy, CV tools, and online safety.",
                        "delivery_mechanism": "4 quarterly workshops per contract year (12 participants/workshop)",
                        "target_beneficiaries": "Underrepresented residents, jobseekers, and older citizens",
                        "annual_volume": 4.0,
                        "toms_metric_code": "NT8",
                        "partner": "Birmingham Community Matters" if has_context else None,
                        "evidence_source": "Retrieved Knowledge Base Document" if has_context else "Synthesized Baseline",
                        "is_from_knowledge_base": has_context
                    },
                    {
                        "name": f"{loc} Youth Tech Mentoring & Work Experience",
                        "theme": "Youth Employment",
                        "location": loc,
                        "description": "Structured career mentoring and technical work experience for young people aged 16-24.",
                        "delivery_mechanism": "Supporting 3 young people per contract year into employment/work pathways",
                        "target_beneficiaries": "Young people (NEET) in Greater Birmingham",
                        "annual_volume": 3.0,
                        "toms_metric_code": "NT3",
                        "partner": "St Basils Youth Charity" if has_context else None,
                        "evidence_source": "Retrieved Knowledge Base Document" if has_context else "Synthesized Baseline",
                        "is_from_knowledge_base": has_context
                    }
                ],
                "expected_impact": [
                    "Direct support for local jobseekers and digitally excluded residents",
                    "Tangible pathways for young people into technology careers"
                ],
                "dependencies": [
                    "Access to local community venues or library facilities",
                    "Infosys volunteer mentor recruitment and safeguarding onboarding"
                ]
            },
            "enhanced_package": {
                "rationale": "High-impact Social Value package delivering elevated commercial score and substantial local community outcomes.",
                "initiatives": [
                    {
                        "name": f"{loc} Digital Inclusion & Hardware Reuse Programme",
                        "theme": "Digital Inclusion",
                        "location": loc,
                        "description": "Comprehensive digital workshops paired with 25 refurbished laptops/devices donated to local families.",
                        "delivery_mechanism": "6 workshops per year + 25 refurbished digital devices donated annually",
                        "target_beneficiaries": "Disadvantaged learners and low-income families",
                        "annual_volume": 25.0,
                        "toms_metric_code": "NT20",
                        "partner": None,
                        "evidence_source": "Retrieved Knowledge Base Document" if has_context else "Enhanced Proposal",
                        "is_from_knowledge_base": has_context
                    },
                    {
                        "name": f"{loc} Tech Apprenticeship Pathway",
                        "theme": "Employment & Skills",
                        "location": loc,
                        "description": "Delivery of certified junior technical apprenticeship weeks for local school leavers.",
                        "delivery_mechanism": "52 apprenticeship training weeks per year delivered on contract work",
                        "target_beneficiaries": "Local apprentices and school leavers",
                        "annual_volume": 52.0,
                        "toms_metric_code": "NT1",
                        "partner": None,
                        "evidence_source": "Retrieved Knowledge Base Document" if has_context else "Enhanced Proposal",
                        "is_from_knowledge_base": has_context
                    },
                    {
                        "name": "STEM & Digital Education Volunteer Outreach",
                        "theme": "Community Engagement",
                        "location": loc,
                        "description": "Infosys technical employees delivering STEM mentoring and coding clubs at regional secondary schools.",
                        "delivery_mechanism": "100 hours of staff volunteering per year",
                        "target_beneficiaries": "Secondary school students in disadvantaged catchments",
                        "annual_volume": 100.0,
                        "toms_metric_code": "NT10",
                        "partner": None,
                        "evidence_source": "Infosys Corporate Social Responsibility Evidence",
                        "is_from_knowledge_base": has_context
                    }
                ],
                "expected_impact": [
                    "Significant uplift in Social Value proxy value surpassing client target weighting",
                    "Sustainable circular hardware donations preventing digital poverty",
                    "Accredited tech skills pipelines for regional talent"
                ],
                "dependencies": [
                    "Asset disposal approval for decommissioned laptops",
                    "Accreditation partnership with regional college/apprenticeship provider"
                ]
            },
            "localised_package": {
                "rationale": f"Hyper-targeted Social Value response aligned specifically with {loc} city council socio-economic priorities.",
                "initiatives": [
                    {
                        "name": f"{loc} Digital Inclusion Workshop",
                        "theme": "Digital Inclusion",
                        "location": loc,
                        "description": "Targeted workshops held in high-deprivation wards to tackle digital literacy barriers.",
                        "delivery_mechanism": "8 targeted sessions per year",
                        "target_beneficiaries": "Local vulnerable adults, elderly, and long-term unemployed",
                        "annual_volume": 8.0,
                        "toms_metric_code": "NT8",
                        "partner": None,
                        "evidence_source": "Retrieved Knowledge Base Document" if has_context else "Localised Proposal",
                        "is_from_knowledge_base": has_context
                    },
                    {
                        "name": f"{loc} SME & Social Enterprise Supply Chain Commitment",
                        "theme": "Economic Growth",
                        "location": loc,
                        "description": "Earmarked procurement and catering spend ringfenced for local West Midlands SMEs and social enterprises.",
                        "delivery_mechanism": "£50,000 annual direct spend directed to local suppliers",
                        "target_beneficiaries": "Local independent businesses and VCSE suppliers",
                        "annual_volume": 50000.0,
                        "toms_metric_code": "NT14",
                        "partner": None,
                        "evidence_source": "Infosys Supply Chain Policy Evidence",
                        "is_from_knowledge_base": has_context
                    }
                ],
                "expected_impact": [
                    "Direct retention of contract wealth within the Birmingham local economy",
                    "Measurable impact on council ward-level digital poverty statistics"
                ],
                "dependencies": [
                    "Council procurement team approval on eligible local postcodes for supply chain spend"
                ]
            },
            "assumptions": [
                f"Client will provide access to local council/community venues in {loc} at nominal or zero cost.",
                "Infosys delivery staff will be permitted 2 working days/year dedicated to Social Value volunteering.",
                "Apprentices will be recruited locally within commuting distance of contract delivery."
            ],
            "validation_required": [
                "Confirm local community partner availability and formal agreement in Birmingham.",
                "Validate whether client accepts National TOMs proxy values or requires a proprietary Social Value measurement tool.",
                "Verify IT equipment availability for device refurbishment and GDPR sanitization protocol."
            ]
        }


# Maintain backward compatible references
openai_service = LLMService()
llm_service = openai_service
